Repository astroboy-lab/astroboy, pull requests merged in 2021-06, with the labels that each got.

#67 支持声明式路由 & 异步化启动
  CHANGELOG
  core/Astroboy.ts
  core/CoreLoader.ts
  core/Loader.ts
  core/lib/util.ts
  docs/.vuepress/config.js
  docs/升级指南/3.X升级指南.md
  docs/基础功能/声明式路由.md
  docs/基础功能/目录结构.md
  docs/基础功能/配置.md
  docs/新手指南/astroboy-cli.md
  loader/AstroboyBootLoader.ts
  loader/AstroboyConfigLoader.ts
  loader/AstroboyControllerLoader.ts
  loader/AstroboyExtendLoader.ts
  loader/AstroboyFnLoader.ts
  loader/AstroboyLibLoader.ts
  loader/AstroboyMiddlewareLoader.ts
  loader/AstroboyPkgLoader.ts
  loader/AstroboyRouterLoader.ts
  loader/AstroboyServiceLoader.ts
  loader/AstroboyVersionFileLoader.ts
  package.json
  plugins/astroboy-body/app/middlewares/astroboy-body.ts
  plugins/astroboy-router/app/middlewares/astroboy-router.ts
  plugins/astroboy-security/app/middlewares/astroboy-security-csp.ts
  plugins/astroboy-security/app/middlewares/astroboy-security-csrf.ts
  plugins/astroboy-security/app/middlewares/astroboy-security-cto.ts
  plugins/astroboy-security/app/middlewares/astroboy-security-frameOptions.ts
  plugins/astroboy-security/app/middlewares/astroboy-security-hsts.ts
  plugins/astroboy-security/app/middlewares/astroboy-security-p3p.ts
  plugins/astroboy-security/app/middlewares/astroboy-security-xss.ts
  plugins/astroboy-security/app/middlewares/astroboy-security-xssProtection.ts
  plugins/astroboy-static/app/middlewares/astroboy-static.ts
  yarn.lock
Labels: dependencies, enhancement

#71 升级 vuepress@^1.8.2
  package.json
  yarn.lock
Labels: dependencies

#72 文档添加 changelog 链接
  CHANGELOG
  docs/.vuepress/config.js
  docs/Changelog.md
Labels: documentation
